Contenidos/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from Contenidos import views

urlpatterns = [
    path(route='',
         view=views.Inicio.as_view(),
         name='index'),

    path(route='documentos/<pk>/',
         view=views.VerDocumento.as_view(),
         name='ver_documento'),

    path(route='documentos/add',
         view=views.CrearDocumento.as_view(),
         name='crear_documento'),

    path(route='documentos/<pk>/editar',
         view=views.EditarContenido.as_view(),
         name='editar_contenido'),

    path(route='documentos/<pk>/eliminar',
         view=views.EliminarDocumento.as_view(),
         name='eliminar_documento'),

    path(route='documentos/pendientes',
         view=views.DocumentosPendientes.as_view(),
         name='documentos_pendientes'),

    path(route='documentos/pendientes/<pk>/aprobar',
         view=views.AprobarDocumento.as_view(),
         name='aprobar_documento'),

]

Portal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('Contenidos.urls','contenidos'), namespace='contenidos')),
    path('',include(('Users.urls','users'), namespace='users')),
   # path('contenidos/documentos/create',)
]

Users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from Users import views

urlpatterns = [
    path(route='usuarios/',
        view=views.Usuarios.as_view(),
        name='usuarios'),

    path(route='usuarios/<pk>/editar/',
        view=views.ActualizarPermiso.as_view(),
        name='editar_usuario'), 
]

Contenidos/models.py
from django.db import models
from django.contrib.auth.models import Group

# Create your models here.

class Documento(models.Model):
    grupo=models.ForeignKey(Group,on_delete=models.CASCADE) # cada documento pertenece a un grupo, no a un usuario
    titulo=models.CharField(max_length=140)
    texto=models.TextField(blank=True,null=True)#por defecto es null
    aprobado=models.BooleanField(null=False,blank=False,default=False)
    created_date = models.DateTimeField(('Date created'), auto_now_add=True)
    modified_date = models.DateTimeField(('Date modified'), auto_now=True)

    def __str__(self): #alias que identifica describe al objeto
        return self.titulo

Users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
# Create your models here.
class User(AbstractUser):
    
    SELECT_TIPO = (('1','Lector'),('2','Editor'))      
    tipo = models.CharField('Tipo de usuario',max_length=20, choices=SELECT_TIPO,default='1')

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email' , 'last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('contenidos:index')

    class Meta(AbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'

Contenidos/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import View
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView  
from django.views.generic.detail import DetailView  
from Users.models import User
from Contenidos.models import Documento
from django.contrib.auth.models import Group

# Create your views here.

class Inicio(ListView):#lista todos los contenidos
    model=Documento
    context_object_name='documentos'
    template_name='cards.html'
    paginate_by=10
    ordering=['-modified_date']

    def get_queryset(self):
        user=self.request.user
        grupoID=user.groups.get().id
        self.queryset=Documento.objects.filter(grupo=grupoID,aprobado=True)
        return super().get_queryset()

class VerDocumento(DetailView):
    model=Documento
    template_name='contenido.html'

class CrearDocumento(CreateView):
    model=Documento
    template_name='crear_contenido.html'
    success_url = reverse_lazy('contenidos:index')
    fields=['titulo','texto','grupo']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user=self.request.user
        context['grupo']=user.groups.get().id
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        user=self.request.user
        grupoID=user.groups.get().id
        if user.is_staff==False:
            adminGrupo=User.objects.get(is_staff=True,groups__id=grupoID)
            mensaje= user.get_full_name() + ' a creado una nueva publicacion.'
            adminGrupo.email_user('Nueva Publicacion', mensaje, from_email=None)
        return response


class EditarContenido(UpdateView):
    model = Documento
    context_object_name='documento'
    template_name='crear_contenido.html'
    fields = ['titulo','texto']
    success_url = reverse_lazy('contenidos:index')

class EliminarDocumento(DeleteView):
    model=Documento
    success_url = reverse_lazy('contenidos:index')
    template_name='documento_confirm_delete.html'

class DocumentosPendientes(ListView):#lista todos los contenidos
    model=Documento
    context_object_name='documentos'
    template_name='contenidos_pendiente.html'
    paginate_by=10
    ordering=['-modified_date']

    def get_queryset(self):
        user=self.request.user
        grupoID=user.groups.get().id
        self.queryset=Documento.objects.filter(grupo=grupoID,aprobado=False)
        return super().get_queryset()

class AprobarDocumento(UpdateView):
    model = Documento
    context_object_name='documento'
    template_name='aprobar_contenido.html'
    fields = ['aprobado']
    success_url = reverse_lazy('contenidos:documentos_pendientes')

Users/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from Users.models import User
from django.views.generic.edit import UpdateView
from django.http import JsonResponse

# Create your views here.

class AjaxableResponseMixin:

    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
            }
            return JsonResponse(data)
        else:
            return response

class Usuarios(ListView):#lista todos los contenidos
    model=User
    context_object_name='usuarios'
    template_name='usuarios.html'
    paginate_by=10
    ordering=['-last_name']

    def get_queryset(self):
        user=self.request.user
        grupoID=user.groups.get().id
        #import pdb; pdb.set_trace()
        self.queryset=User.objects.filter(groups=grupoID)
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        context=super(Usuarios,self).get_context_data(**kwargs)   
        context['tipos']=(('1','Lector'),('2','Editor'))
        return context

class ActualizarPermiso(AjaxableResponseMixin,UpdateView):
    model=User
    fields=['tipo']

templates/aprobar_contenido.html
{% extends "index.html" %}

{% block content %}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Mis publicaciones</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{% url 'contenidos:index' %}">Inicio</a></li>
                    <li class="breadcrumb-item active">Mis publicaciones</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Content Header (Page header) -->

<section class="content">
    <div class="container-fluid">
        <!-- Small Box (Stat card) -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                
                <h2 >Aprobar Contenido</h2>
                <form method="post">{% csrf_token %}
        
                    <div class="col-lg-12 mb">
                        <label>Si aprueba este contenido sera visible por todos los miembros de su grupo.</label>
                    </div>
        
                    <input type="hidden"name="aprobado" value="True" >

                    <div class="float-right">
                        <button type="submit" class="btn btn-success">
                            Confirmar</button>
                    </div>
                    
                </form>
                    <!-- ./col -->
                </div>
                <!-- /.row -->

            </div><!-- /.container-fluid -->
        </section>
        <!-- /.row -->
    </div>
</section>


<!-- /.content -->

{% endblock %}

templates/cards.html
{% extends "index.html" %}

{% block content %}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Mis documentos</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{% url 'contenidos:index' %}">Inicio</a></li>
                    <li class="breadcrumb-item active">Mis documentos</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Content Header (Page header) -->

<section class="content">
    <div class="container-fluid">
        <!-- Small Box (Stat card) -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <div class="row">
                    {%for documento in documentos%}
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>{{documento.titulo|title|truncatechars:11}}</h3>
                                <!--<p>{{documento.texto|capfirst|truncatechars:16}}...</p>-->
                            </div>
                            <div class="icon">
                                <i class="ion ion-image"></i>
                            </div>

                            <a href="{% url 'contenidos:editar_contenido' documento.id %}"
                                class="small-box-footer">Editar <i class="fas fa-arrow-circle-right"></i></a>
                            <a href="{% url 'contenidos:eliminar_documento' documento.id %}"
                                class="small-box-footer bg-danger">Eliminar <i
                                    class="fas fa-arrow-circle-right"></i></a>
                        </div>

                    </div>
                    {%endfor%}
                    <!-- ./col -->
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class=" paginations-steps">
                        <nav aria-label="Navegación de páguina">
                            <ul class="pagination  ">
                                {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                                <li class="page-item"><a class="page-link"
                                        href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                                </li>
                                {% endif %}

                                <li class="page-item active">
                                    <span class="page-link">
                                        {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                                        <span class="sr-only">(current)</span>
                                    </span>
                                </li>
                                {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link"
                                        href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                                </li>
                                <li class="page-item"><a class="page-link"
                                        href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                                </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>

            </div><!-- /.container-fluid -->

        </section>
        <!-- /.row -->
    </div>
</section>


<!-- /.content -->

{% endblock %}

templates/contenidos_pendiente.html
{% extends "index.html" %}

{% block content %}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Mis documentos</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{% url 'contenidos:index' %}">Inicio</a></li>
                    <li class="breadcrumb-item active">Mis documentos</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Content Header (Page header) -->

<section class="content">
    <div class="container-fluid">
        <!-- Small Box (Stat card) -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <div class="row">
                    {%for documento in documentos%}
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>{{documento.titulo|title|truncatechars:11}}</h3>
                                <!--<p>{{documento.texto|capfirst|truncatechars:16}}...</p>-->
                            </div>
                            <div class="icon">
                                <i class="ion ion-image"></i>
                            </div>

                            <a href="{% url 'contenidos:aprobar_documento' documento.id %}"
                                class="small-box-footer">Aprobar <i class="fas fa-arrow-circle-right"></i></a>
                            <a href="{% url 'contenidos:eliminar_documento' documento.id %}"
                                class="small-box-footer bg-danger">Eliminar <i
                                    class="fas fa-arrow-circle-right"></i></a>
                        </div>

                    </div>
                    {%endfor%}
                    <!-- ./col -->
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class=" paginations-steps">
                        <nav aria-label="Navegación de páguina">
                            <ul class="pagination  ">
                                {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                                <li class="page-item"><a class="page-link"
                                        href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                                </li>
                                {% endif %}

                                <li class="page-item active">
                                    <span class="page-link">
                                        {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                                        <span class="sr-only">(current)</span>
                                    </span>
                                </li>
                                {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link"
                                        href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                                </li>
                                <li class="page-item"><a class="page-link"
                                        href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                                </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>

            </div><!-- /.container-fluid -->

        </section>
        <!-- /.row -->
    </div>
</section>


<!-- /.content -->

{% endblock %}

templates/documento_confirm_delete.html
{% extends "index.html" %}

{% block content %}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Mis publicaciones</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{% url 'contenidos:index' %}">Inicio</a></li>
                    <li class="breadcrumb-item active">Mis publicaciones</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Content Header (Page header) -->

<section class="content">
    <div class="container-fluid">
        <!-- Small Box (Stat card) -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                
                <h2 >Eliminar Anuncio</h2>
                <form method="post">{% csrf_token %}
        
                    <div class="col-lg-12 mb">
                        <label>Si elimina este documento, no podra volver a recuperarlo.</label>
                    </div>
        
                    
                    <div class="float-right">
                        <button type="submit" class="btn btn-success">
                            Confirmar</button>
                    </div>
                    
                </form>
                    <!-- ./col -->
                </div>
                <!-- /.row -->

            </div><!-- /.container-fluid -->
        </section>
        <!-- /.row -->
    </div>
</section>


<!-- /.content -->

{% endblock %}

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block titulo %}Administración Provincial de Energía{% endblock titulo %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="shortcut icon" href="{% static 'dist/img/logo.png' %}" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">

 
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.css' %}">

  <link rel="stylesheet" href="{% static 'dist/css/style.css' %}">

  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <link href="//rawgithub.com/indrimuska/jquery-editable-select/master/dist/jquery-editable-select.min.css" rel="stylesheet">
  <script src="jquery-3.4.1.min.js"></script>
</head>

<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-light navbar-white">
      <!-- Left navbar links -->
      <!--<ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="#" class="nav-link">Inicio</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="#" class="nav-link">Contactos</a>
        </li>-->
      </ul>
      <!-- SEARCH FORM -->
      <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
          <input class="form-control form-control-navbar" type="search" placeholder="Buscar" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-navbar" type="submit">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div>
      </form>
      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown user-menu">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
            <img src="{% static 'dist/img/imagesworker.jpg' %}" class="user-image img-circle elevation-2"
              alt="User Image">
            <span class="d-none d-md-inline">{{ user.username }}</span>
          </a>
          <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <!-- User image -->
            <li class="user-header bg-primary">
              <img src="{% static 'dist/img/imagesworker.jpg' %}" class="img-circle elevation-2" alt="User Image">
              <p>
                {{ user.get_full_name }}
                <!--<small></small>-->
              </p>
            </li>
            <!-- Menu Body -->
            <!-- Menu Footer-->
            <li class="user-footer">
              <a href="#" class="btn btn-default btn-flat">Perfil</a>
              <a href="#" class="btn btn-default btn-flat float-right">Cerrar Sesión</a>
            </li>
          </ul>
        </li>
        <!-- Notifications Dropdown Menu -->
      </ul>
    </nav>
    <!-- /.navbar -->
    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-light-orange elevation-4">
      <!-- Brand Logo -->
      <a href="{% url 'contenidos:index' %}" class="brand-link navbar-light">
        <img src="{% static 'dist/img/logo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
          style="opacity: .8">
        <span class="brand-text font-weight-light"><b>CONT</b>enidos</span>
      </a>
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-header"></li>
            <li class="nav-item has-treeview">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-plus-square"></i>
                <p>
                  Nuevo
                  <i class="fas fa-angle-left right"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="{% url 'contenidos:crear_documento' %}" class="nav-link">
                    <i class="nav-icon fas fa-edit"></i>
                    <p>Documento</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-calculator"></i>
                    <p>Hoja de Cálculo</p>
                  </a>
                </li>
              </ul>
            </li>
            {%if user.is_staff%}
            <li class="nav-item has-treeview">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-plus-square"></i>
                <p>
                  Contenidos
                  <i class="fas fa-angle-left right"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="{% url 'contenidos:documentos_pendientes' %}" class="nav-link">
                    <i class="nav-icon fas fa-edit"></i>
                    <p>Pendientes</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-calculator"></i>
                    <p>Aprobados</p>
                  </a>
                </li>
              </ul>
            </li>
            <li class="nav-item has-treeview">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-plus-square"></i>
                <p>
                  Grupo
                  <i class="fas fa-angle-left right"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="{% url 'users:usuarios' %}" class="nav-link">
                    <i class="nav-icon fas fa-edit"></i>
                    <p>Usuarios</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-calculator"></i>
                    <p>Permisos</p>
                  </a>
                </li>
              </ul>
            </li>
            {%endif%}
          </ul>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      {% block content %}
      <!-- /.content -->
      {% endblock %}
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
      <strong><a href="#">Contenidos</a></strong>
      <div class="float-right d-none d-sm-inline-block">
        <b>La Pampa</b>
      </div>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
  </div>
  <!-- ./wrapper -->
  <!-- jQuery -->
  <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
  <!-- jQuery UI 1.11.4 -->
  <script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
  <!-- Ajax -->
  <script src="{% static 'dist/js/djangoAjax.js' %}"></script>
  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
  <script>
    $.widget.bridge('uibutton', $.ui.button)
  </script>
  <!-- Bootstrap 4 -->
  <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- Summernote -->
  <script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
  <!-- overlayScrollbars -->
  <script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static 'dist/js/adminlte.js' %}"></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  <script src="{% static 'dist/js/pages/dashboard.js' %}"></script>

  

  
  <!-- SweetAlert -->
  <script src="{% static 'dist/js/sweetalert.min.js' %}"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="{% static 'dist/js/demo.js' %}"></script>

  <script src="{% static 'dist/js/pages/usuario.js' %}"></script>

  

</body>

</html>

templates/usuarios.html
{% extends "index.html" %}

{% block content %}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Usuarios</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{% url 'contenidos:index' %}">Inicio</a></li>
                    <li class="breadcrumb-item active">Usuarios</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Editar permisos</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Usuario</th>
                                    <th>Permiso</th>
                                    <th class="text-center">Lector/Editor</th>
                                </tr>
                            </thead>
                            <tbody id="mitabla">
                                {% for usuario in usuarios %}
                                <tr>
                                    <td>{{usuario.first_name|title}} {{usuario.last_name|title}}</td>
                                    <td>{{usuario.email}} </td>
                                    <td class="text-center">
                                        <select id="permiso" onchange="actualizar({{usuario.id}})"
                                            data-url="{% url 'users:editar_usuario' usuario.id %}">
                                            <option value='1' {% ifequal usuario.tipo '1' %} selected {%endifequal%}>
                                                Lector</option>
                                            <option value='2' {% ifequal usuario.tipo '2' %} selected {%endifequal%}>
                                                Editor</option>
                                        </select>

                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-footer -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
<script>
    function actualizar(userID) {
        var url = "/usuarios/" + userID + "/editar/";
        var tipo=$("#permiso").val();
        $.post(url, { tipo: tipo },
            function (data, status) {

            }).fail(function () {
                alert("Algo salio mal! Recarge la pagina y vuelva a intentarlo.");
            })
    };

</script>

<!-- /.content -->
{% endblock %}